{{ if eq .chezmoi.os "darwin" -}}
neovim-bin = "${HOME}/.brew/bin/nvim"
frame = "transparent" # options: full, none. macOS only: transparent, buttonless
title-hidden = true # macOS only
{{ else -}}
frame = "full" # options: full, none. macOS only: transparent, buttonless
{{ end -}}

grid = "{{ if .tags.thinkpad.enabled }}{{ if ge (20 | sub .env.cols) 10 }}{{ 20 | sub .env.cols }}{{ else }}{{ .env.cols }}{{ end }}{{ else }}{{ .env.cols }}{{ end }}x{{ if .tags.thinkpad.enabled }}{{ if ge (5 | sub .env.rows) 10 }}{{ 5 | sub .env.rows }}{{ else }}{{ .env.rows }}{{ end }}{{ else }}{{ .env.rows }}{{ end }}"

mouse-cursor-icon = "arrow"
tabs = false
srgb = true

[font]
normal = {{ .env.font | quote }} # Will use the bundled Fira Code Nerd Font by default
size = {{ if or (.tags.zephyrus.enabled) (.tags.thinkpad.enabled) }}{{ if ge (4 | sub .env.fontSize) 10 }}{{ 4 | sub .env.fontSize }}{{ else }}{{ .env.fontSize }}{{ end }}{{ else }}{{ .env.fontSize }}{{ end }}
