modmap:
  - name: Capslock
    remap:
      Capslock:
        held: Control_L
        alone: ESC
        alone_timeout_millis: 200
  - name: PCKeyboard
    remap:
      SUPER_L: ALT_L
      SUPER_R: ALT_R
      ALT_L: SUPER_L
      ALT_R: SUPER_R
    device:
      not: ["NuPhy NuPhy Air75 HE", "NuPhy NuPhy Air75 HE Keyboard"]

keymap:
  - name: Terminals
    application:
      only: ["/foot/", "/foot-client/", "/alacritty/", "/kitty/"]
    remap:
      SUPER-c: Control-Shift-c
      SUPER-v: Control-Shift-v
      SUPER-x: Shift-Delete
    exact_match: true
  - name: Global
    remap:
      SUPER-a: Control-a
      SUPER-c: Control-c
      SUPER-v: Control-v
      SUPER-x: Control-x
      SUPER-n: Control-n
      SUPER-t: Control-t
    exact_match: true
