modmap:
	- name: CapsLock
		exact_match: true
    remap:
      Capslock:
        held: Control_L
        alone: ESC
        alone_timeout_millis: 200

modmap:
  - name: PCKeyboard
		exact_match: true
		remap:
			SUPER_L: ALT_L
			SUPER_R: ALT_R
			ALT_R: SUPER_R
    device:
      not: [nuphy-nuphy-air75-he, nuphy-nuphy-air75-he-keyboard]

keymap:
  - name: Terminals
		exact_match: true
    application:
      only: ["/foot/", "/foot-client/", "/alacritty/", "/kitty/"]
		remap:
			SUPER-c: Control-Shift-c
			SUPER-v: Control-Shift-v
			SUPER-x: Shift-Delete

keymap:
  - name: Global
		exact_match: true
		remap:
			SUPER-a: Control-a
			SUPER-c: Control-c
			SUPER-v: Control-v
			SUPER-x: Control-x
			SUPER-n: Control-n
			SUPER-t: Control-t
