[core]
	darwin = [
		"bash",
		"zsh",
		"diffutils",
		"dos2unix",
		"curl",
		"git",
		"gawk",
		"gnu-sed",
		"gnu-tar",
		"gzip",
		"star",
		"screen",
		"telnet",
		"tree",
		"unzip",
		"watch",
		"wget",
	]
	arch = [
		"bash",
		"bash-completion",
		"zsh",
		"extra/zsh-completions",
		"less",
		"man-db",
		"cpio",
		"dos2unix",
		"diffutils",
		"curl",
		"git",
		"inetutils",
		"less",
		"tree",
		"screen",
		"tar",
		"unzip",
		"wget",
		"which",
		"glibc-locales",
	]

[core.tags]
