[k8sCli]
	darwin = [
		"kubectl",
		"krew",
		"k9s",
		"stern",
		"helm",
	]
	arch = [
		"kubectl",
		"krew",
		"k9s",
		"stern",
		"helm",
	]
	krew = [
		"ctr",
		"ctx",
		"exec-as",
		"fuzzy",
		"mtail",
		"ns",
		"node-admin",
		"node-restart",
		"node-shell",
		"restart",
		"view-allocations",
		"view-secret",
		"view-utilization",
		"unused-volumes",
	]

[k8sCli.tags]
	go = true
