[neovim]
	darwin = [
		"neovim",
		"lua-language-server",
	]
	arch = [
		"neovim",
		"lua-language-server",
	]
	pip = [
		"neovim",
		"pynvim",
		"flake8",
		"yamllint",
		"ruff",
		"gitlint",
	]
	npm = [
		"neovim",
		"cspell",
	]
	rocks = [
		"jsregexp",
	]
	go = [
		"github.com/go-delve/delve/cmd/dlv@latest",
		"github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2",
	]
	gem = [
		"neovim",
	]

[neovim.tags]
	python3 = true
	nodejs = true
	lua	= true
	go = true
	ruby = true
	rust = true
	terminalMultiplexer = true
	gitCli = true
	devCore = true
