[browsers]
	darwin = [
		"librewolf",
		"waterfox",
		"ungoogled-chromium",
	]
	arch = [
		"librewolf",
		"waterfox",
		"ungoogled-chromium",
	]

[web]
	ytUserAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"

[browsers.tags]
